### ISSUE TITLE
failed with error code 1 in

### ISSUE THREAD

**Issue by dipenpatel235** [paulo-raca/mongofs#1]
pip install mongofs
Collecting mongofs
  Downloading mongofs-0.1.0.2.tar.gz
Collecting RouteFS (from mongofs)
  Downloading RouteFS-1.2.0.tar.gz
Collecting notify2 (from mongofs)
  Downloading notify2-0.3.tar.gz
Requirement already satisfied: pymongo in /usr/lib64/python2.7/site-packages (from mongofs)
Collecting expiringdict (from mongofs)
  Downloading expiringdict-1.1.3.tar.gz
Collecting procfs (from mongofs)
  Downloading procfs-0.5.0.tar.gz
Collecting fuse_python>=0.2a (from RouteFS->mongofs)
  Downloading fuse-python-0.2.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 2.1MB/s
    Complete output from command python setup.py egg_info:
    pkg-config unavailable, build terminated

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oQpfmG/fuse-python/

**Comment by paulo-raca** [comment]
The `python-fuse` dependency doesn't play along with pip very well.
On ubuntu I have to install it from apt-get: `sudo apt-get install python-fuse`

I hope this helps

**Comment by dipenpatel235** [comment]
Thanks.
I have cent os 7
So which package I required to install ?

Thanks

**Comment by paulo-raca** [comment]
Not sure, but I think it is fuse-python
